name: ci

on: [push]

jobs:
  tests:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        # os: ["ubuntu-18.04", "macos-10.15", "windows-2019"]
        os: ["ubuntu-18.04"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      # - uses: goanpeca/setup-miniconda@v1.5.0
      #   with:
      #     auto-update-conda: true
      #     environment-file: environment.yml
      #     python-version: ${{ matrix.python-version }}
      - name: Install Procgen Build
        run: python -m pip install -e procgen-build
      - name: Test
        run: python -u -m procgen_build.dev_test
      # - name: Build and publish
      #   # env:
      #     # TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     # TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     echo twine upload dist/*
